version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - MISTRAL_API_KEY=${MISTRAL_API_KEY}
      - LANGBASE_API_KEY=${LANGBASE_API_KEY}
      - LANGBASE_PIPE_ID=${LANGBASE_PIPE_ID}
      - DAYTONA_API_URL=${DAYTONA_API_URL}
      - DAYTONA_API_KEY=${DAYTONA_API_KEY}
      - DATABASE_URL=${DATABASE_URL}
    depends_on:
      - postgres
    networks:
      - app-network

  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=ai_codebase_agent
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - app-network

volumes:
  postgres_data:
  redis_data:

networks:
  app-network:
    driver: bridge
